env:
  # APP_NAME is normally the same as your pipeline slug
  # if that isn't true, update here
  APP_NAME: ${BUILDKITE_PIPELINE_SLUG}

steps:
  - label: ":golangci-lint: lint :lint-roller:"
    key: "lint"
    plugins:
      - docker#v5.8.0:
          image: "golang:1.20"
          command: |
            make lint

  - label: ":test_tube: test"
    key: "gotest"
    plugins:
      - docker#v5.8.0:
          image: "golang:1.20"
          command: |
            make test

  - label: ":golang: build"
    key: "gobuild"
    artifact_paths: "bin/${APP_NAME}"
    plugins:
      - docker#v5.8.0:
          image: "golang:1.20"
          environment:
            - APP_NAME
          command: |
            make build
