-- +goose Up
ALTER TABLE issuers
ALTER COLUMN id TYPE VARCHAR;
ALTER TABLE issuers
ALTER COLUMN owner_id TYPE VARCHAR;
ALTER TABLE user_info
ALTER COLUMN id TYPE VARCHAR;
ALTER TABLE user_info
ALTER COLUMN iss_id TYPE VARCHAR;
ALTER TABLE oauth_clients
ALTER COLUMN id TYPE VARCHAR;
ALTER TABLE oauth_clients
ALTER COLUMN owner_id TYPE VARCHAR;
