-- +goose Up
ALTER TABLE issuers ALTER COLUMN id TYPE STRING;
ALTER TABLE issuers ALTER COLUMN tenant_id TYPE STRING;

ALTER TABLE user_info ALTER COLUMN id TYPE STRING;
ALTER TABLE user_info ALTER COLUMN iss_id TYPE STRING;

ALTER TABLE oauth_clients ALTER COLUMN id TYPE STRING;
ALTER TABLE oauth_clients ALTER COLUMN tenant_id TYPE STRING;
