---
{{- $serverPort := include "idapi.listenPort" . }}
{{- $serverIP := .Values.config.server.ip }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.name" . }}-app-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  {{- with .Values.config }}
  identity-api.yaml: |
    server:
      listen: "{{ $serverIP }}:{{ $serverPort }}"
    otel:
      enabled: {{ .otel.enabled | default false }}
      {{- if .otel.enabled }}
      provider: {{ .otel.provider }}
      stdout:
        prettyPrint: {{ .otel.stdout.prettyPrint }}
      otlp:
        endpoint: {{ .otel.otlp.endpoint }}
        insecure: {{ .otel.otlp.insecure }}
      {{- end }}
    oauth:
      issuer: {{ .oauth.issuer | quote}}
      accessTokenLifespan: {{ .oauth.accessTokenLifespan }}
      privateKeys:
        {{- if .oauth.privateKeys.keys }}
        {{- range $i, $value := .oauth.privateKeys.keys }}
        - keyID: {{ $value.keyID }}
          path: {{ $value.path }}
          algorithm: {{ $value.algorithm }}
        {{- end }}
        {{- end }}
    storage:
      type: crdb
  {{- end }}
